### ISSUE TITLE
the mod is not working after steam vr update

### ISSUE THREAD

**Issue by btteamss** [Fishbiter/WMR_vrclient#1]
it seems that after the latest update of steam vr,the mod is not working,when i launch the steam vr,it crash.

**Comment by cyraxi** [comment]
Have same issue since steam vr update.

I had to remove this mod.
I hope you guys can fix it soon. Love it using joystick instead of touchpad.

**Comment by AidanROTF** [comment]
Easy fix is to delete all of the dll files then verify integrity of steam vr. If steamVR works after that try reinstalling the mod. That worked for me.

**Comment by cyraxi** [comment]
thx that worked suggestion by AidanROTF

**Comment by Fishbiter** [comment]
Yes, you need to make sure to remove the real_vrclient and real_vrclient_x86 dlls before running the install script again.
